/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          primary: "var(--color-bg-primary)",
          secondary: "var(--color-bg-secondary)",
          tertiary: "var(--color-bg-tertiary)",
          elevated: "var(--color-bg-elevated)",
          inverse: "var(--color-bg-inverse)",
          overlay: "var(--color-bg-overlay)",
          skeleton: "var(--color-bg-skeleton)",
        },
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          muted: "var(--color-text-muted)",
          inverse: "var(--color-text-inverse)",
          disabled: "var(--color-text-disabled)",
        },
        border: {
          DEFAULT: "var(--color-border-default)",
          default: "var(--color-border-default)",
          strong: "var(--color-border-strong)",
          subtle: "var(--color-border-subtle)",
          focus: "var(--color-border-focus)",
          error: "var(--color-border-error)",
        },
        interactive: {
          hover: "var(--color-hover-bg)",
          "hover-strong": "var(--color-hover-bg-strong)",
          active: "var(--color-active-bg)",
          selected: "var(--color-selected-bg)",
          "selected-strong": "var(--color-selected-bg-strong)",
          ring: "var(--color-focus-ring)",
        },
        input: {
          bg: "var(--color-input-bg)",
          border: "var(--color-input-border)",
          "border-focus": "var(--color-input-border-focus)",
          placeholder: "var(--color-input-placeholder)",
          "disabled-bg": "var(--color-input-disabled-bg)",
        },
        brand: {
          DEFAULT: "var(--color-brand-primary)",
          hover: "var(--color-brand-hover)",
          active: "var(--color-brand-active)",
          surface: "var(--color-brand-surface)",
          "surface-strong": "var(--color-brand-surface-strong)",
          border: "var(--color-brand-border)",
          "border-strong": "var(--color-brand-border-strong)",
          text: "var(--color-brand-text)",
          contrast: "var(--color-brand-contrast)",
        },
        status: {
          "success-surface": "var(--color-success-surface)",
          "success-text": "var(--color-success-text)",
          "success-border": "var(--color-success-border)",
          "warning-surface": "var(--color-warning-surface)",
          "warning-text": "var(--color-warning-text)",
          "warning-border": "var(--color-warning-border)",
          "error-surface": "var(--color-error-surface)",
          "error-text": "var(--color-error-text)",
          "error-border": "var(--color-error-border)",
          "info-surface": "var(--color-info-surface)",
          "info-text": "var(--color-info-text)",
          "info-border": "var(--color-info-border)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        'fluid-xs': 'var(--text-xs)',
        'fluid-sm': 'var(--text-sm)',
        'fluid-base': 'var(--text-base)',
        'fluid-lg': 'var(--text-lg)',
        'fluid-xl': 'var(--text-xl)',
        'fluid-2xl': 'var(--text-2xl)',
        'fluid-3xl': 'var(--text-3xl)',
        'fluid-4xl': 'var(--text-4xl)',
        'fluid-5xl': 'var(--text-5xl)',
        'fluid-6xl': 'var(--text-6xl)',
        'heading-1': 'var(--heading-1)',
        'heading-2': 'var(--heading-2)',
        'heading-3': 'var(--heading-3)',
        'heading-4': 'var(--heading-4)',
        'heading-5': 'var(--heading-5)',
        'heading-6': 'var(--heading-6)',
      },
      spacing: {
        'fluid-1': 'var(--space-1)',
        'fluid-2': 'var(--space-2)',
        'fluid-3': 'var(--space-3)',
        'fluid-4': 'var(--space-4)',
        'fluid-5': 'var(--space-5)',
        'fluid-6': 'var(--space-6)',
        'fluid-8': 'var(--space-8)',
        'fluid-10': 'var(--space-10)',
        'fluid-12': 'var(--space-12)',
        'fluid-16': 'var(--space-16)',
        'page-x': 'var(--page-padding-x)',
        'page-y': 'var(--page-padding-y)',
        'safe-top': 'var(--safe-area-top)',
        'safe-bottom': 'var(--safe-area-bottom)',
        'safe-left': 'var(--safe-area-left)',
        'safe-right': 'var(--safe-area-right)',
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
        card: "var(--radius-card)",
        button: "var(--radius-button)",
        input: "var(--radius-input)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
      },
      transitionDuration: {
        fast: "var(--duration-fast, 140ms)",
        normal: "var(--duration-normal, 220ms)",
        slow: "var(--duration-slow, 350ms)",
      },
      transitionTimingFunction: {
        "out-smooth": "cubic-bezier(0.16, 1, 0.3, 1)",
        "in-out-smooth": "cubic-bezier(0.65, 0, 0.35, 1)",
        "spring": "cubic-bezier(0.175, 0.885, 0.32, 1.1)",
      },
      animation: {
        "page-enter": "pageEntrance var(--duration-normal) cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "message-enter": "messageEntrance var(--duration-normal) cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "dialog-enter": "dialogEntrance var(--duration-normal) cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "solid-pulse": "solidPulse 1.6s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "cursor-blink": "cursorBlink 550ms step-end infinite",
      },
      zIndex: {
        dropdown: "1000",
        sticky: "1100",
        drawer: "1200",
        overlay: "1300",
        modal: "1400",
        toast: "1500",
        tooltip: "1600",
        max: "9999",
      },
      screens: {
        'xs': '320px',
        'mobile': '375px',
        'mobile-lg': '430px',
        'tablet': '640px',
        'tablet-lg': '768px',
        'desktop': '1024px',
        'desktop-lg': '1280px',
        'wide': '1440px',
        'ultrawide': '1920px',
        '2k': '2560px',
      },
      maxWidth: {
        'container-sm': 'var(--container-sm)',
        'container-md': 'var(--container-md)',
        'container-lg': 'var(--container-lg)',
        'container-xl': 'var(--container-xl)',
        'container-2xl': 'var(--container-2xl)',
        'sidebar-collapsed': 'var(--sidebar-width-collapsed)',
        'sidebar-default': 'var(--sidebar-width-default)',
        'sidebar-wide': 'var(--sidebar-width-wide)',
      },
      minWidth: {
        'touch': 'var(--touch-target)',
      },
      height: {
        'header': 'var(--header-height)',
        'input': 'var(--input-height)',
        'input-sm': 'var(--input-height-sm)',
        'button': 'var(--button-height)',
        'button-sm': 'var(--button-height-sm)',
        'button-lg': 'var(--button-height-lg)',
        'icon-btn': 'var(--icon-button-size)',
        'icon-btn-sm': 'var(--icon-button-size-sm)',
      },
      width: {
        'touch': 'var(--touch-target)',
      },
    },
  },
  plugins: [],
}
