/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          primary: "var(--color-bg-primary)",
          secondary: "var(--color-bg-secondary)",
          tertiary: "var(--color-bg-tertiary)",
          elevated: "var(--color-bg-elevated)",
          inverse: "var(--color-bg-inverse)",
          overlay: "var(--color-bg-overlay)",
          skeleton: "var(--color-bg-skeleton)",
        },
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          muted: "var(--color-text-muted)",
          inverse: "var(--color-text-inverse)",
          disabled: "var(--color-text-disabled)",
        },
        border: {
          DEFAULT: "var(--color-border-default)",
          default: "var(--color-border-default)",
          strong: "var(--color-border-strong)",
          subtle: "var(--color-border-subtle)",
          focus: "var(--color-border-focus)",
          error: "var(--color-border-error)",
        },
        interactive: {
          hover: "var(--color-hover-bg)",
          "hover-strong": "var(--color-hover-bg-strong)",
          active: "var(--color-active-bg)",
          selected: "var(--color-selected-bg)",
          "selected-strong": "var(--color-selected-bg-strong)",
          ring: "var(--color-focus-ring)",
        },
        input: {
          bg: "var(--color-input-bg)",
          border: "var(--color-input-border)",
          "border-focus": "var(--color-input-border-focus)",
          placeholder: "var(--color-input-placeholder)",
          "disabled-bg": "var(--color-input-disabled-bg)",
        },
        status: {
          "success-surface": "var(--color-success-surface)",
          "success-text": "var(--color-success-text)",
          "success-border": "var(--color-success-border)",
          "warning-surface": "var(--color-warning-surface)",
          "warning-text": "var(--color-warning-text)",
          "warning-border": "var(--color-warning-border)",
          "error-surface": "var(--color-error-surface)",
          "error-text": "var(--color-error-text)",
          "error-border": "var(--color-error-border)",
          "info-surface": "var(--color-info-surface)",
          "info-text": "var(--color-info-text)",
          "info-border": "var(--color-info-border)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
      },
      transitionDuration: {
        fast: "100ms",
        normal: "150ms",
        slow: "200ms",
        slower: "300ms",
      },
      zIndex: {
        dropdown: "1000",
        sticky: "1100",
        drawer: "1200",
        overlay: "1300",
        modal: "1400",
        toast: "1500",
        tooltip: "1600",
        max: "9999",
      },
      screens: {
        mobile: "0px",
        tablet: "640px",
        desktop: "1024px",
        wide: "1440px",
      },
    },
  },
  plugins: [],
}
