"""Initial schema

Revision ID: 701d4e9ea3b5
Revises: 
Create Date: 2026-09-30 08:52:56.205390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701d4e9ea3b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_share_token'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_updated_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.add_column('documents', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('storage_path', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('documents', 'id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('documents', 'uploaded_by',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Uuid(),
               nullable=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_unique_constraint(None, 'documents', ['storage_path'])
    op.create_foreign_key(None, 'documents', 'profiles', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'size_str')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'doc_type')
    op.drop_column('documents', 'filename')
    op.add_column('messages', sa.Column('chat_id', sa.Uuid(), nullable=False))
    op.add_column('messages', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('messages', 'id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chat_sessions', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'sender')
    op.drop_column('messages', 'conversation_id')
    op.add_column('shared_chats', sa.Column('chat_id', sa.Uuid(), nullable=False))
    op.add_column('shared_chats', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.alter_column('shared_chats', 'id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('shared_chats', 'share_token',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_index(op.f('ix_shared_chats_conversation_id'), table_name='shared_chats')
    op.create_index(op.f('ix_shared_chats_chat_id'), 'shared_chats', ['chat_id'], unique=False)
    op.create_index(op.f('ix_shared_chats_created_by'), 'shared_chats', ['created_by'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'shared_chats', type_='foreignkey')
    op.create_foreign_key(None, 'shared_chats', 'chat_sessions', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shared_chats', 'profiles', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_column('shared_chats', 'is_active')
    op.drop_column('shared_chats', 'conversation_id')
    op.add_column('students', sa.Column('profile_id', sa.Uuid(), nullable=True))
    op.add_column('students', sa.Column('student_id', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('students', sa.Column('course_id', sa.Uuid(), nullable=False))
    op.add_column('students', sa.Column('division', sa.String(length=10), nullable=False))
    op.add_column('students', sa.Column('enrollment_year', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('students', 'id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.drop_index(op.f('ix_students_department'), table_name='students')
    op.drop_index(op.f('ix_students_enrollment_status'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_index(op.f('ix_students_year'), table_name='students')
    op.create_index(op.f('ix_students_course_id'), 'students', ['course_id'], unique=False)
    op.create_index(op.f('ix_students_full_name'), 'students', ['full_name'], unique=False)
    op.create_index(op.f('ix_students_profile_id'), 'students', ['profile_id'], unique=False)
    op.create_index(op.f('ix_students_semester'), 'students', ['semester'], unique=False)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    op.create_foreign_key(None, 'students', 'courses', ['course_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'students', 'profiles', ['profile_id'], ['id'], ondelete='SET NULL')
    op.drop_column('students', 'avatar_url')
    op.drop_column('students', 'gpa')
    op.drop_column('students', 'department')
    op.drop_column('students', 'course')
    op.drop_column('students', 'year')
    op.drop_column('students', 'joining_year')
    op.drop_column('students', 'name')
    op.drop_column('students', 'roll_number')
    op.drop_column('students', 'advisor_name')
    op.drop_column('students', 'enrollment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('enrollment_status', sa.VARCHAR(length=50), nullable=False))
    op.add_column('students', sa.Column('advisor_name', sa.VARCHAR(length=255), nullable=True))
    op.add_column('students', sa.Column('roll_number', sa.VARCHAR(length=50), nullable=False))
    op.add_column('students', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.add_column('students', sa.Column('joining_year', sa.INTEGER(), nullable=True))
    op.add_column('students', sa.Column('year', sa.VARCHAR(length=50), nullable=False))
    op.add_column('students', sa.Column('course', sa.VARCHAR(length=100), nullable=False))
    op.add_column('students', sa.Column('department', sa.VARCHAR(length=100), nullable=False))
    op.add_column('students', sa.Column('gpa', sa.FLOAT(), nullable=False))
    op.add_column('students', sa.Column('avatar_url', sa.VARCHAR(length=500), nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'students', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_semester'), table_name='students')
    op.drop_index(op.f('ix_students_profile_id'), table_name='students')
    op.drop_index(op.f('ix_students_full_name'), table_name='students')
    op.drop_index(op.f('ix_students_course_id'), table_name='students')
    op.create_index(op.f('ix_students_year'), 'students', ['year'], unique=False)
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=1)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_enrollment_status'), 'students', ['enrollment_status'], unique=False)
    op.create_index(op.f('ix_students_department'), 'students', ['department'], unique=False)
    op.alter_column('students', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('students', 'status')
    op.drop_column('students', 'enrollment_year')
    op.drop_column('students', 'division')
    op.drop_column('students', 'course_id')
    op.drop_column('students', 'full_name')
    op.drop_column('students', 'student_id')
    op.drop_column('students', 'profile_id')
    op.add_column('shared_chats', sa.Column('conversation_id', sa.VARCHAR(length=64), nullable=False))
    op.add_column('shared_chats', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'shared_chats', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'shared_chats', type_='foreignkey')
    op.create_foreign_key(None, 'shared_chats', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_shared_chats_created_by'), table_name='shared_chats')
    op.drop_index(op.f('ix_shared_chats_chat_id'), table_name='shared_chats')
    op.create_index(op.f('ix_shared_chats_conversation_id'), 'shared_chats', ['conversation_id'], unique=False)
    op.alter_column('shared_chats', 'share_token',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('shared_chats', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('shared_chats', 'created_by')
    op.drop_column('shared_chats', 'chat_id')
    op.add_column('messages', sa.Column('conversation_id', sa.VARCHAR(length=64), nullable=False))
    op.add_column('messages', sa.Column('sender', sa.VARCHAR(length=50), nullable=False))
    op.add_column('messages', sa.Column('status', sa.VARCHAR(length=50), nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.alter_column('messages', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'role')
    op.drop_column('messages', 'chat_id')
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(length=255), nullable=False))
    op.add_column('documents', sa.Column('doc_type', sa.VARCHAR(length=100), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(length=500), nullable=True))
    op.add_column('documents', sa.Column('size_str', sa.VARCHAR(length=50), nullable=False))
    op.add_column('documents', sa.Column('uploaded_at', sa.DATETIME(), nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'documents', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.alter_column('documents', 'uploaded_by',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('documents', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'file_name')
    op.drop_column('documents', 'description')
    op.drop_column('documents', 'title')
    op.create_table('conversations',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_message_preview', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_shared', sa.BOOLEAN(), nullable=False),
    sa.Column('share_token', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_share_token'), 'conversations', ['share_token'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_active', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    # ### end Alembic commands ###
